// Subsequences of String {Code studio}
// see directly from code studio
// You are given a string 'STR' containing lowercase English letters from a to z inclusive. Your task is to find all non-empty possible subsequences of 'STR'.
// A Subsequence of a string is the one which is generated by deleting or more letters from the string and keeping the rest of the letters in the same order.
// Sample Input 1:
// abc
// Sample Output 1:
// a ab abc ac b bc c




#include <bits/stdc++.h> 
// https://youtu.be/V0IgCltYgg4
// see from 16min
void solve(vector<string>& ans, string str, string output, int i) {
    //base case
    if(i>=str.length()) {
        if(output.length()>0)
        ans.push_back(output);
        return ;
        }
    
    //exclude
    solve(ans, str, output, i+1);
    //include
    output.push_back(str[i]);
    solve(ans, str, output, i+1);
}

vector<string> subsequences(string str){
	
	vector<string> ans;
    string output = "";
    solve(ans,str,output,0);
    return ans;
	
}
